version: '3.9'

services:
  layer1:
    build:
      context: .
      dockerfile: ./layer1/Dockerfile
    container_name: layer1
    env_file:
      - ./layer1/.env
    ports:
      - "8545:8545"
    volumes:
      - ./shared:/app/shared
    networks:
      - blockchain-net
    # entrypoint: ["/bin/sh"]
    # command: ["-c", "sleep infinity"]

  layer2:
    build:
      context: .
      dockerfile: ./layer2/Dockerfile
    container_name: layer2
    depends_on:
      - layer1
    env_file:
      - ./layer2/.env
    volumes:
      - ./shared:/app/shared
      - ./analytics/logs:/app/analytics/logs
    networks:
      - blockchain-net

networks:
  blockchain-net:
    driver: bridge
