name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate ZK artifacts and verifiers
        working-directory: ./zk
        run: |
          npx hardhat zkit make
          npx hardhat zkit verifiers

      - name: Run tests
        working-directory: ./zk
        run: npx hardhat test 